<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Car;
use App\Models\CarOffer;
use App\Models\Store;
use App\Models\CarBrand;
use App\Models\CarModel;
use App\Models\CarType;

class CarImportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        echo "Starting car import seeding...\n";

        // Car data organized by store username
        $storesCarsData = [
            'sufiyancardeal' => [
                [
                    'name' => 'Corolla',
                    'model' => 'Corolla',
                    'year' => 2020,
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Corolla',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 5000,
                    'priority' => 10,
                ],
                [
                    'name' => 'Civic',
                    'model' => 'Civic',
                    'year' => 2020,
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Honda',
                    'model_name' => 'Civic',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 8000,
                    'priority' => 5,
                ],
                [
                    'name' => 'Corolla X',
                    'model' => 'Corolla X',
                    'year' => 2020,
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Corolla X',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 5000,
                ],
                [
                    'name' => 'Civic RS',
                    'model' => 'Civic RS',
                    'year' => 2021,
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Honda',
                    'model_name' => 'Civic RS',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 13000,
                ],
                [
                    'name' => 'Civic X',
                    'model' => 'Civic X',
                    'year' => 2021,
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Honda',
                    'model_name' => 'Civic X',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 8000,
                ],
                [
                    'name' => 'Land Cruiser Prado V8',
                    'model' => 'Land Cruiser',
                    'year' => 2021,
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Land Cruiser',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 25000,
                    'priority' => 15,
                ],
                [
                    'name' => 'Fortuner',
                    'model' => 'Fortuner',
                    'year' => 2020,
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Fortuner',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 13000,
                ],
                [
                    'name' => 'Rivo',
                    'model' => 'Rivo',
                    'year' => 2020,
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Revo',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 10000,
                ],
                [
                    'name' => 'Honda BRV',
                    'model' => 'Honda BRV',
                    'year' => 2020,
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Honda',
                    'model_name' => 'Honda BRV',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 8000,
                ],
                [
                    'name' => 'Audi A3',
                    'model' => 'Audi A3',
                    'year' => 2019,
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Audi',
                    'model_name' => 'A3',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 20000,
                ],
                [
                    'name' => 'Audi A4',
                    'model' => 'Audi A4',
                    'year' => 2017,
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Audi',
                    'model_name' => 'A4',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 25000,
                ],
                [
                    'name' => 'Audi A5',
                    'model' => 'Audi A5',
                    'year' => 2017,
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Audi',
                    'model_name' => 'A5',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 35000,
                ],
                [
                    'name' => 'Audi A6',
                    'model' => 'Audi A6',
                    'year' => 2021,
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Audi',
                    'model_name' => 'A6',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 50000,
                ],
                [
                    'name' => 'Mercedes Benz AMG C200',
                    'model' => 'Mercedes',
                    'year' => 2018,
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Mercedes',
                    'model_name' => 'Mercedes',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 30000,
                ],
                [
                    'name' => 'Mercedes Benz AMG C180',
                    'model' => 'Mercedes',
                    'year' => 2018,
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Mercedes',
                    'model_name' => 'Mercedes',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 30000,
                ],
                [
                    'name' => 'BMW',
                    'model' => 'BMW',
                    'year' => 2019,
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'BMW',
                    'model_name' => 'BMW',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 40000,
                ],
                [
                    'name' => 'Revo',
                    'model' => 'Revo',
                    'year' => 2020,
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Revo',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 10000,
                ],
                [
                    'name' => 'Karwan Hijet BRV 7 SeaterS',
                    'model' => 'Karwan Hijet BRV 7 SeaterS',
                    'year' => 2020,
                    'color' => 'N/A',
                    'seats' => 6,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Suzuki',
                    'model_name' => 'Karwan',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 8000,
                ],
            ],

            'startransportservices' => [
                [
                    'name' => 'Corolla X',
                    'model' => 'Corolla',
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Corolla',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 6000,
                ],
                [
                    'name' => 'Land Cruiser Prado',
                    'model' => 'Land Cruiser',
                    'color' => 'N/A',
                    'seats' => 7,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Land Cruiser',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 14000,
                ],
                [
                    'name' => 'Fortuner',
                    'model' => 'Fortuner',
                    'color' => 'N/A',
                    'seats' => 7,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Fortuner',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 14000,
                ],
                [
                    'name' => 'Revo',
                    'model' => 'Revo',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Diesel',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Revo',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 10000,
                ],
                [
                    'name' => 'Civic',
                    'model' => 'Civic',
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Honda',
                    'model_name' => 'Civic',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 8000,
                ],
                [
                    'name' => 'Revo New',
                    'model' => 'Revo',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Diesel',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Revo',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 12000,
                ],
            ],

            'nsrentacar' => [
                [
                    'name' => 'Corolla X',
                    'model' => 'Corolla',

                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Corolla',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 6000,
                ],
                [
                    'name' => 'Land Cruiser Prado',
                    'model' => 'Land Cruiser',

                    'color' => 'N/A',
                    'seats' => 7,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Land Cruiser',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 14000,
                ],
                [
                    'name' => 'Fortuner',
                    'model' => 'Fortuner',

                    'color' => 'N/A',
                    'seats' => 7,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Fortuner',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 14000,
                ],
                [
                    'name' => 'Revo',
                    'model' => 'Revo',

                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Diesel',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Revo',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 10000,
                ],
                [
                    'name' => 'Civic',
                    'model' => 'Civic',

                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Honda',
                    'model_name' => 'Civic',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 8000,
                ],
                [
                    'name' => 'Civic New',
                    'model' => 'Civic',
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Honda',
                    'model_name' => 'Civic',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 12000,
                ],
            ],

            'ahmedrentacar' => [
                [
                    'name' => 'X Corolla',
                    'model' => 'Corolla',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Corolla',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 5000,
                ],
                [
                    'name' => 'Revo',
                    'model' => 'Revo',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Diesel',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Revo',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 12000,
                ],
                [
                    'name' => 'Fortuner',
                    'model' => 'Fortuner',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 7,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Fortuner',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 15000,
                ],
                [
                    'name' => 'Land Cruiser V8',
                    'model' => 'Land Cruiser',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 7,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Land Cruiser',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 25000,
                ],
                [
                    'name' => 'Land Cruiser Prado',
                    'model' => 'Land Cruiser',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 7,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Land Cruiser',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 15000,
                ],
                [
                    'name' => 'Mira',
                    'model' => 'Mira',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Daihatsu',
                    'model_name' => 'Mira',
                    'type_name' => 'Hatchback',
                    'with_driver_rate' => 5000,
                ],
                [
                    'name' => 'Mercedes',
                    'model' => 'Mercedes',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Mercedes',
                    'model_name' => 'Mercedes',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 20000,
                ],
                [
                    'name' => 'Audi',
                    'model' => 'Audi',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Audi',
                    'model_name' => 'Audi',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 20000,
                ],
                [
                    'name' => 'Civic',
                    'model' => 'Civic',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Honda',
                    'model_name' => 'Civic',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 10000,
                ],
                [
                    'name' => 'Limousine',
                    'model' => 'Limousine',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 6,
                    'transmission' => 'automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Limousine',
                    'model_name' => 'Limousine',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 40000,
                ],
            ],
            'hamidrenta' => [
                [
                    'name' => 'Corolla',
                    'model' => 'Corolla GLI',
                    'year' => 2020,
                    'color' => 'Black',
                    'seats' => 4,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Corolla GLi',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 6000,
                ],
                [
                    'name' => 'Civic',
                    'model' => 'Civic',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Honda',
                    'model_name' => 'Civic',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 9500,
                ],
                [
                    'name' => 'Revo',
                    'model' => 'Revo',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Revo',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 14000,
                ],
                [
                    'name' => 'Fortuner',
                    'model' => 'Fortuner',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 7,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Fortuner',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 16000,
                ],
                [
                    'name' => 'Land Cruiser Prado',
                    'model' => 'Land Cruiser',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 7,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Land Cruiser',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 16000,
                ],
            ],
            'faraztransport' => [
                [
                    'name' => 'Mercedes',
                    'model' => 'Mercedes',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Mercedes',
                    'model_name' => 'Mercedes',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 25000,
                ],
                [
                    'name' => 'Land Cruiser Prado',
                    'model' => 'Land Cruiser',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 7,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Land Cruiser',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 15000,
                ],
                [
                    'name' => 'BMW',
                    'model' => 'BMW',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'BMW',
                    'model_name' => 'BMW',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 40000,
                ],
                [
                    'name' => 'Revo',
                    'model' => 'Revo',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Revo',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 10000,
                ],
                [
                    'name' => 'Civic New',
                    'model' => 'Civic',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Honda',
                    'model_name' => 'Civic',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 12000,
                ],
                [
                    'name' => 'Civic X',
                    'model' => 'Civic X',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Honda',
                    'model_name' => 'Civic X',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 8000,
                ],
                [
                    'name' => 'Corolla X',
                    'model' => 'Corolla X',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Corolla X',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 5000,
                ],
                [
                    'name' => 'Land Cruiser V8 LC-200',
                    'model' => 'Land Cruiser',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 7,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Land Cruiser',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 22000,
                ],
                [
                    'name' => 'Land Cruiser V8 LC-300',
                    'model' => 'Land Cruiser',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 7,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Land Cruiser',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 25000,
                ],
                [
                    'name' => 'Audi A3',
                    'model' => 'A3',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Audi',
                    'model_name' => 'A3',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 19000,
                ],
                [
                    'name' => 'Audi A4',
                    'model' => 'A4',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Audi',
                    'model_name' => 'A4',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 23000,
                ],
                [
                    'name' => 'Yaris',
                    'model' => 'Yaris',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Yaris',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 5000,
                ],
                [
                    'name' => 'GMC',
                    'model' => 'GMC',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 7,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'GMC',
                    'model_name' => 'GMC',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 45000,
                ],
            ],
            'farhanrentacar' => [
                [
                    'name' => 'Alto',
                    'model' => 'Alto',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Suzuki',
                    'model_name' => 'Alto',
                    'type_name' => 'Hatchback',
                    'with_driver_rate' => 4500,
                ],
                [
                    'name' => 'Mira',
                    'model' => 'Mira',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Daihatsu',
                    'model_name' => 'Mira',
                    'type_name' => 'Hatchback',
                    'with_driver_rate' => 4500,
                ],
                [
                    'name' => 'WagonR',
                    'model' => 'WagonR',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Suzuki',
                    'model_name' => 'WagonR',
                    'type_name' => 'Hatchback',
                    'with_driver_rate' => 4500,
                ],
                [
                    'name' => 'Cultus',
                    'model' => 'Cultus',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 4,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Suzuki',
                    'model_name' => 'Cultus',
                    'type_name' => 'Hatchback',
                    'with_driver_rate' => 4500,
                ],
                [
                    'name' => 'Corolla Facelift',
                    'model' => 'Corolla',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Corolla',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 5000,
                ],
                [
                    'name' => 'Corolla X New',
                    'model' => 'Corolla X',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Corolla X',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 7500,
                ],
                [
                    'name' => 'Yaris',
                    'model' => 'Yaris',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Yaris',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 6000,
                ],
                [
                    'name' => 'Yaris New',
                    'model' => 'Yaris',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Yaris',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 7500,
                ],
                [
                    'name' => 'Civic X',
                    'model' => 'Civic X',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Honda',
                    'model_name' => 'Civic X',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 8000,
                ],
                [
                    'name' => 'Civic New',
                    'model' => 'Civic',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Honda',
                    'model_name' => 'Civic',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 14000,
                ],
                [
                    'name' => 'Sportage',
                    'model' => 'Sportage',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Kia',
                    'model_name' => 'Sportage',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 13000,
                ],
                [
                    'name' => 'Tucson',
                    'model' => 'Tucson',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Hyundai',
                    'model_name' => 'Tucson',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 13000,
                ],
                [
                    'name' => 'Honda BRV',
                    'model' => 'Honda BRV',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 7,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Honda',
                    'model_name' => 'Honda BRV',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 9000,
                ],
                [
                    'name' => 'Toyota Revo',
                    'model' => 'Revo',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Revo',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 10000,
                ],
                [
                    'name' => 'Toyota Rocco',
                    'model' => 'Rocco',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Rocco',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 13000,
                ],
                [
                    'name' => 'Toyota Revo GR',
                    'model' => 'Revo',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Revo',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 15000,
                ],
                [
                    'name' => 'Land Cruiser V8 LC200',
                    'model' => 'Land Cruiser',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 7,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Land Cruiser',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 28000,
                ],
                [
                    'name' => 'Land Cruiser V8 LC300',
                    'model' => 'Land Cruiser',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 7,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Land Cruiser',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 32000,
                ],
                [
                    'name' => 'Land Cruiser Prado',
                    'model' => 'Land Cruiser',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 7,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Land Cruiser',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 18000,
                ],
                [
                    'name' => 'Toyota Fortuner',
                    'model' => 'Fortuner',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 7,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Toyota',
                    'model_name' => 'Fortuner',
                    'type_name' => 'SUV',
                    'with_driver_rate' => 18000,
                ],
                [
                    'name' => 'Mercedes',
                    'model' => 'Mercedes',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Mercedes',
                    'model_name' => 'Mercedes',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 30000,
                ],
                [
                    'name' => 'Audi A3',
                    'model' => 'Audi',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Audi',
                    'model_name' => 'A3',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 24000,
                ],
                [
                    'name' => 'Audi A5',
                    'model' => 'Audi A5',
                    'year' => 'N/A',
                    'color' => 'N/A',
                    'seats' => 5,
                    'transmission' => 'Automatic',
                    'fuel_type' => 'Petrol',
                    'brand_name' => 'Audi',
                    'model_name' => 'A5',
                    'type_name' => 'Sedan',
                    'with_driver_rate' => 30000,
                ],
            ]

        ];

        // Process each store's cars
        foreach ($storesCarsData as $storeUsername => $carsData) {
            // Get the store by username
            $store = Store::where('store_username', $storeUsername)->first();
            if (!$store) {
                echo "Store with username '{$storeUsername}' not found. Skipping...\n";
                continue;
            }

            echo "Processing store: {$store->name} (Username: {$storeUsername}, ID: {$store->id})\n";

            foreach ($carsData as $carData) {
            // Find or create brand
            $brand = CarBrand::firstOrCreate(
                ['name' => $carData['brand_name']],
                ['name' => $carData['brand_name']]
            );

            // Find or create model with unique slug handling
            $existingModel = CarModel::where('car_brand_id', $brand->id)
                ->where('name', $carData['model_name'])
                ->first();

            if (!$existingModel) {
                $baseSlug = \Illuminate\Support\Str::slug($carData['model_name']);
                $slug = $baseSlug;
                $counter = 1;

                // Check if slug already exists
                while (CarModel::where('slug', $slug)->exists()) {
                    $slug = $baseSlug . '-' . $counter;
                    $counter++;
                }

                $model = CarModel::create([
                    'car_brand_id' => $brand->id,
                    'name' => $carData['model_name'],
                    'slug' => $slug,
                ]);
            } else {
                $model = $existingModel;
            }

            // Find or create car type
            $carType = CarType::firstOrCreate(
                ['name' => $carData['type_name']],
                ['name' => $carData['type_name']]
            );

            // Check if car already exists
            $existingCar = Car::where('store_id', $store->id)
                ->where('name', $carData['name'])
                ->where('model', $carData['model'])
                ->first();

            if (!$existingCar) {
                // Create the car
                $car = Car::create([
                    'store_id' => $store->id,
                    'car_brand_id' => $brand->id,
                    'car_model_id' => $model->id,
                    'car_type_id' => $carType->id,
                    'model' => $carData['model'],
                    'year' => $carData['year'] ?? null,
                    'name' => $carData['name'],
                    'color' => $carData['color'],
                    'description' => null,
                    'image_urls' => null,
                    'seats' => $carData['seats'],
                    'transmission' => $carData['transmission'],
                    'fuel_type' => $carData['fuel_type'],
                    'priority' => $carData['priority'] ?? 0,
                ]);

                // Create car offer with driver rate
                CarOffer::create([
                    'car_id' => $car->id,
                    'price_with_driver' => $carData['with_driver_rate'],
                    'price_without_driver' => null,
                    'currency' => 'PKR',
                    'available_from' => now(),
                    'available_to' => now()->addYear(),
                    'is_active' => true,
                    'start_date' => null,
                    'end_date' => null,
                ]);

                echo "Created car: {$carData['name']} ({$brand->name} {$model->name}) - Rate: {$carData['with_driver_rate']}\n";
            } else {
                echo "Car already exists: {$carData['name']}\n";
            }
            }
        }

        echo "Car import seeding completed!\n";
    }
}
